name: CI
on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10, 12]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node V${{ matrix.node_version }}
        uses: actions/setup-node@v2.1.0
        with:
            version: ${{ matrix.node_version }}
      - name: install
        run: npm install